[profile.default]
auto_detect_remappings = false
libs = ["lib"]
src = "contracts"
test = "tests"
out = "artifacts"
cache_path = "cache"
bytecode_hash = "none"
cbor_metadata = false
verbosity = 3
fs_permissions = [{ access = "read", path = "./artifacts"}]

# NOTE: Specifying shanghai as the evm_version seems required for the Goerli tests to pass
evm_version = "shanghai"

# NOTE: Remappings are somewhat limited right now as there's no way to apply them to specific contexts: https://github.com/foundry-rs/foundry/issues/1855
remappings = [
  # Used by us directly.
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-solc-0.6/=lib/openzeppelin-solc-0.6/contracts/",
  "openzeppelin-solc-0.7/=lib/openzeppelin-solc-0.7/contracts/",
  "openzeppelin-solc-0.8/=lib/openzeppelin-solc-0.8/contracts/",
  "uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts/",

  # Used by uniswap v3 internally.
  "@uniswap/v3-core/=lib/uniswap-v3-core/",
  "@openzeppelin/contracts/=lib/openzeppelin-solc-0.6/contracts/",
]

[profile.default.optimizer_details]
yul = false

[rpc_endpoints]
mainnet = "${ETHEREUM_NODE_MAINNET}"
polygon = "${ETHEREUM_NODE_POLYGON}"
goerli = "${ETHEREUM_NODE_GOERLI}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_MAINNET}", chain = "mainnet" }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}", chain = "polygon" }
